# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/mahyar-86/UnrealEngine/Linux_Unreal_Engine_5.5.4

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	MenuSystem_EOS_Steam-Android-DebugGame  \
	MenuSystem_EOS_Steam-Android-Development  \
	MenuSystem_EOS_Steam-Android-Shipping  \
	MenuSystem_EOS_Steam-Linux-DebugGame  \
	MenuSystem_EOS_Steam-Linux-Development  \
	MenuSystem_EOS_Steam-Linux-Shipping  \
	MenuSystem_EOS_Steam-LinuxArm64-DebugGame  \
	MenuSystem_EOS_Steam-LinuxArm64-Development  \
	MenuSystem_EOS_Steam-LinuxArm64-Shipping  \
	MenuSystem_EOS_Steam \
	MenuSystem_EOS_SteamEditor-Linux-DebugGame  \
	MenuSystem_EOS_SteamEditor-Linux-Development  \
	MenuSystem_EOS_SteamEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MenuSystem_EOS_SteamEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MenuSystem_EOS_SteamEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

MenuSystem_EOS_Steam-Android-DebugGame:
	 $(BUILD) MenuSystem_EOS_Steam Android DebugGame  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-Android-Development:
	 $(BUILD) MenuSystem_EOS_Steam Android Development  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-Android-Shipping:
	 $(BUILD) MenuSystem_EOS_Steam Android Shipping  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-Linux-DebugGame:
	 $(BUILD) MenuSystem_EOS_Steam Linux DebugGame  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-Linux-Development:
	 $(BUILD) MenuSystem_EOS_Steam Linux Development  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-Linux-Shipping:
	 $(BUILD) MenuSystem_EOS_Steam Linux Shipping  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-LinuxArm64-DebugGame:
	 $(BUILD) MenuSystem_EOS_Steam LinuxArm64 DebugGame  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-LinuxArm64-Development:
	 $(BUILD) MenuSystem_EOS_Steam LinuxArm64 Development  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam-LinuxArm64-Shipping:
	 $(BUILD) MenuSystem_EOS_Steam LinuxArm64 Shipping  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_Steam: MenuSystem_EOS_Steam-Linux-Development

MenuSystem_EOS_SteamEditor-Linux-DebugGame:
	 $(BUILD) MenuSystem_EOS_SteamEditor Linux DebugGame  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_SteamEditor-Linux-Development:
	 $(BUILD) MenuSystem_EOS_SteamEditor Linux Development  -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" $(ARGS)

MenuSystem_EOS_SteamEditor: MenuSystem_EOS_SteamEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/mahyar-86/UnrealEngine/UnrealProjects/MenuSystem_EOS_Steam/MenuSystem_EOS_Steam.uproject" -Game 

.PHONY: $(TARGETS)
